web:
  build: .
  environment:
    MYENV: virtualEnv
  volumes:
    - .:/code
web_makemigrations:
  extends:
    service: web
  command: python innosoftFinanzas/manage.py makemigrations
web_migrate:
  extends:
    service: web
  command: python innosoftFinanzas/manage.py migrate
web_run:
  extends:
    service: web
  command: python innosoftFinanzas/manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"
web_test:
  extends: 
    service: web
  command: python innosoftFinanzas/manage.py test inventario necesidades