# Generated by Django 3.2.8 on 2021-12-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('necesidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='necesidad',
            name='comite',
        ),
        migrations.DeleteModel(
            name='Comite',
        ),
        migrations.DeleteModel(
            name='Necesidad',
        ),
    ]
